spring:
  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/gps_auth_db}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}