spring:
  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${PORT}

jwt:
  secret-key: ${JWT_SECRET_KEY}

email:
  sendgrid-base-url: https://api.sendgrid.com/v3
  secret-key: ${EMAIL_SECRET_KEY}
  sender-address: geoloc.iua@gmail.com
  recovery:
    url: https://gps-front.herokuapp.com/reset-password/
  welcome:
    url: https://gps-front.herokuapp.com/reset-password/
